### ISSUE TITLE
basic setup not working

### ISSUE THREAD

**Issue by MikBin** [TechingCrewMatt/com-techingcrew-cordova-adcolony#1]
Hi,
I've installed the plugin and run on android simulator using test code at point 2. replacing 
'xxxxAppIdxxxx', 'xxxxZoneIdxxxx' with proper data generate on adcolony backend panel.
when calling initColony() on deviceready  I just have the following string error logged and nothing more:
onRequestNotFilled
am I doing something wrong?
are you using this plugin in production?
thanks
Michele

**Comment by TechingCrewMatt** [comment]
Sorry, I didn't see this issue. Yes, we use this plugin in production. 

If you are still having this problem, please let me know. It's most likely because AdColony doesn't have a video to deliver. Do you get the same error with your development credentials? The sample ads should fill every time.

**Comment by TechingCrewMatt** [comment]
Sorry, I didn't see this issue. Yes, we do use it in production.

Are you still having this problem? Did you try using test credentials?
